# Generated by Django 3.0.6 on 2020-06-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_film_cate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='cate',
            new_name='category',
        ),
    ]
