# Generated by Django 3.0.6 on 2020-06-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20200605_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.CharField(choices=[('افلام', 'افلام')], default='افلام', max_length=100),
        ),
    ]
