# Generated by Django 3.0.6 on 2020-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='download_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='watch',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='download_url',
            field=models.URLField(null=True),
        ),
    ]
