# Generated by Django 3.0.6 on 2020-06-04 14:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200604_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='watch',
            field=ckeditor.fields.RichTextField(max_length=255, null=True),
        ),
    ]
