# Generated by Django 3.0.6 on 2020-06-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20200604_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='download_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='watch',
            field=models.TextField(default='', null=True),
        ),
    ]
