# Generated by Django 3.0.6 on 2020-06-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20200604_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='category', to='page.FilmTags'),
        ),
    ]
