# Generated by Django 3.0.6 on 2020-06-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20200604_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.ManyToManyField(related_name='series', to='page.Category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='films', to='page.Category'),
        ),
    ]
