# Generated by Django 3.0.6 on 2020-06-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20200604_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
    ]
