# Generated by Django 3.0.6 on 2020-06-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_film_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(default='افلام', related_name='films', to='page.Category'),
        ),
    ]
