# Generated by Django 3.0.6 on 2020-06-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_film_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
    ]
