# Generated by Django 3.0.6 on 2020-06-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20200605_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='category',
        ),
        migrations.AddField(
            model_name='episode',
            name='category',
            field=models.CharField(default='مسلسلات', max_length=100),
        ),
    ]
