# Generated by Django 3.0.6 on 2020-06-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20200605_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='category',
            field=models.CharField(choices=[('مسلسلات', 'مسلسلات')], default='مسلسلات', max_length=100),
        ),
    ]
